M19G2/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using M19G2.IBLL;
using M19G2.Models;
using M19G2.SessionStorage;

using System.Threading;

namespace M19G2.Controllers
{
    [Authorize(Roles = "Client")]
    public class CartController : BaseController
    {
        private readonly ISessionStorage sessionStorage;
        private readonly IDishService dishService;
        private readonly IOrdersService ordersService;
        private readonly IUserService userService;
        private readonly IOrderQueueService queueService;

        public CartController(ISessionStorage ss, IDishService ds, IOrdersService ordersService, IUserService userService,
            IOrderQueueService qservice)
        {
            queueService = qservice;
            this.userService = userService;
            sessionStorage = ss;
            dishService = ds;
            this.ordersService = ordersService;
        }

        public ActionResult Index(bool? completedPurchase, int? oldId, string errorMessage)
        {
            var model = new CartViewModel();
            model.Dishes = new List<DishDto>();
            model.Quantities = new Dictionary<int, int>();

            if(!string.IsNullOrEmpty(errorMessage))
            {
                ViewBag.ErrorMessage = errorMessage;
                return View(model);
            }

            if (!completedPurchase.HasValue || (completedPurchase.HasValue && !completedPurchase.Value))
            {
                if (sessionStorage.IsOrderReady())
                {
                    var corder = sessionStorage.GetCurrentOrder();
                    corder.CurrentOrder.DishesIDs.ForEach(x => model.Dishes.Add(dishService.GetDishByID(x)));
                    model.CurrentOrder = corder.CurrentOrder;
                    model.CurrentOrder.Message = "";
                    model.Quantities = corder.Quantities;
                    model.UserAddresses = new List<SelectListItem>();
                    model.CalledFromNav = true;

                    userService.GetUserAddresses(CurrentUser.Id).ToList().ForEach(x => model.UserAddresses.Add(new SelectListItem() { Value = x.ID.ToString(), Text = x.Name }));
                }
                else
                {
                    sessionStorage.ResetOrder(CurrentUser.Id);
                    model.CurrentOrder = sessionStorage.GetCurrentOrder().CurrentOrder;
                    model.CurrentOrder.Message = "";
                }
                model.Completed = false;
            }
            else
            {
                if (completedPurchase.Value)
                {
                    ViewBag.OldId = oldId.Value;
                    model.Completed = true;
                    model.CurrentOrder = sessionStorage.GetCurrentOrder().CurrentOrder;
                }
            }

            return View(model);
        }


        [HttpGet]
        public ActionResult Remove(int id)
        {
            if (sessionStorage.IsOrderReady())
            {
                sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.RemoveAll(x => x == id);
            }
            var dishes = new List<DishDto>();
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.ForEach(did => {
                dishes.Add(dishService.GetDishByID(did));
            });

            var orderReviewModel = new CartViewModel()
            {
                CurrentOrder = sessionStorage.GetCurrentOrder().CurrentOrder,
                Dishes = dishes,
                CalledFromNav = true,
                UserAddresses = new List<SelectListItem>(),
                Quantities = sessionStorage.GetCurrentOrder().Quantities
            };

            userService.GetUserAddresses(CurrentUser.Id).ToList().ForEach(x => orderReviewModel.UserAddresses.Add(new SelectListItem() { Value = x.ID.ToString(), Text = x.Name }));

            return PartialView("_cartListView", orderReviewModel);
        }

        private void WaitThread(object id)
        {
            Thread.Sleep(1);
            queueService.PushOrder((int)id);
        }

        [HttpPost]
        public ActionResult CompleteCheckout(string extraDetails, string deliveryAddress)
        {
            OrderDto finalOrder = new OrderDto();
            finalOrder = sessionStorage.GetCurrentOrder().CompileOrder();
            finalOrder.Message = extraDetails;
            finalOrder.AddressID = int.Parse(deliveryAddress);

            bool canComplete = true;
            string errorDish = "";
            finalOrder.DishesIDs.ForEach(x =>
            {
                var dish = dishService.GetDishByID(x);
                if(!dish.IsActive)
                {
                    canComplete = false;
                    errorDish = dish.Name;
                }
            });
            if(!canComplete)
            {
                sessionStorage.ResetOrder(CurrentUser.Id);
                return RedirectToAction("Index", new { errorMessage = $"{errorDish} is not available anymore, your order cannot be completed." });
            }

            var id = ordersService.CreateNewOrder(finalOrder);
            //queueService.PushOrder(id);
            new Thread(WaitThread).Start(id);
            sessionStorage.ResetOrder(CurrentUser.Id);

            return RedirectToAction("Index", new { completedPurchase = true, oldId = id });
        }

        [HttpGet]
        public ActionResult GetCartNum()
        {
            if (!sessionStorage.IsOrderReady())
                return Content("Cart (0)");
            else
            {
                var numOfItems = sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.Count;
                return Content($"Cart ({ numOfItems })");
            }
        }
    }
}

M19G2/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using M19G2.Models;
using M19G2.IBLL;
using M19G2.SessionStorage;
using M19G2.Filters;
using System.IO;

namespace M19G2.Controllers
{
    public class DishController : BaseController
    {
        private readonly IDishService dishService;
        private readonly ISessionStorage sessionStorage;

        public DishController(IDishService dishService, ISessionStorage sessionStorage)
        {
            this.dishService = dishService;
            this.sessionStorage = sessionStorage;
        }

        [Authorize(Roles = "Client")]
        public ActionResult Index()
        {
            var cc = dishService.GetActiveDishes() as List<DishDto>;

            return View(new DishesViewModel() { Dishes = cc });
        }

        [HttpGet]
        public FileResult ShowImage(int dishId)
        {
            var dishesImgs = dishService.GetImagesForDish(dishId);
            ImageDto img;

            if (dishesImgs.Count > 0)
                img = dishesImgs.ElementAt(0);  // first image 
            else
                img = dishService.GetImageById(1);  // default image

            return File(img.Data, "image");
        }

        [HttpGet]
        public FileResult ShowDishImage(int imageId)
        {
            return File(dishService.GetImageById(imageId).Data, "image");
        }

        [Authorize(Roles = "Chef")]
        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase uploadedImage, int dishId)
        {
            using (MemoryStream memsr = new MemoryStream())
            {
                uploadedImage.InputStream.CopyTo(memsr);
                int imageId;
                dishService.UploadImage(memsr.ToArray(), dishId, out imageId);
            }
            return RedirectToAction("EditDish", "KitchenChef", new { id = dishId });
        }

        [Authorize]
        public ActionResult ViewDish(int id)
        {
            var dish = dishService.GetDishByID(id);

            return View("ViewDish", new ViewDishModel() { Dish = dish });
        }

        [Authorize(Roles = "Chef")]
        [HttpGet]
        public EmptyResult RemoveImage(int imageId)
        {
            dishService.RemoveImage(imageId);
            return new EmptyResult();
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult RenderDishFilter()
        {
            DishFilterViewModel model = new DishFilterViewModel
            {
                DishTypes = dishService.GetAllDishTypes().Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.Name }).ToList()
            };

            return PartialView("_DishesFilter", model);
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult Filter(string dishFilterName, string dishFilterTypeName, double? maxPrice, double? minPrice, string[] ingredients, bool? clearFilters)
        {
            var shit = new DishesViewModel()
            {
                Dishes = new List<DishDto>(),
                Types = new List<DishTypeDto>()
            };

            var filter = new Filter<DishDto>(dishService.GetActiveDishes());

           if(!clearFilters.HasValue || !clearFilters.Value)
            {
                if (!string.IsNullOrEmpty(dishFilterName))
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.Name.ToLower().Contains(dishFilterName.ToLower())));
                if (!string.IsNullOrEmpty(dishFilterTypeName))
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.DishType == int.Parse(dishFilterTypeName)));
                if (minPrice.HasValue)
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.Price >= (decimal)minPrice.Value));
                if (maxPrice.HasValue)
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.Price <= (decimal)maxPrice.Value));
                if (ingredients != null && ingredients.Length > 0)
                {
                    foreach (var ingredient in ingredients)
                        filter.FilterDefinitions.Add(new FilterDefinition<DishDto>((x) =>
                        {
                            foreach (var v in x.Ingredients)
                                if (v.Name == ingredient)
                                    return true;
                            return false;
                        }));  // huh this might take a bit..
                }
            }

            shit.Dishes = filter.ApplyFilters().ToList();

            return PartialView("_ListDishes", shit);
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult Remove(int id)
        {
            if (sessionStorage.IsOrderReady())
            {
                sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.RemoveAll(x => x == id);
            }
            var dishes = new List<DishDto>();
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.ForEach(did => dishes.Add(dishService.GetDishByID(did)));

            var orderReviewModel = new CartViewModel()
            {
                CurrentOrder = sessionStorage.GetCurrentOrder().CurrentOrder,
                Dishes = dishes
            };

            return PartialView("_cartListView", orderReviewModel);
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult Purchase(int id)
        {
            if (!sessionStorage.IsOrderReady())
                sessionStorage.ResetOrder(CurrentUser.Id);

            var dish = dishService.GetDishByID(id);
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.Add(id);

            var dishes = new List<DishDto>();
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.ForEach(did => {
                dishes.Add(dishService.GetDishByID(did));
            });

            var orderReviewModel = new CartViewModel()
            {
                CurrentOrder = sessionStorage.GetCurrentOrder().CurrentOrder,
                Dishes = dishes,
                Quantities = sessionStorage.GetCurrentOrder().Quantities
            };
            orderReviewModel.CalledFromNav = false;

            return PartialView("_cartReview", orderReviewModel);
        }
    }
}

M19G2/Controllers/TaxiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using M19G2.Models;
using M19G2.IBLL;

namespace M19G2.Controllers
{
    [Authorize(Roles = "Delivery Service Staff")]
    public class TaxiController : BaseController
    {
        private readonly IDeliveryService deliveryService;
        private readonly IOrdersService ordersService;
        private readonly IUserService userService;
        private readonly IDeliveryAutomation deliveryAutomation;

        public TaxiController(IDeliveryService deliveryService, IOrdersService ordersService, IUserService userService, IDeliveryAutomation deliveryAutomation)
        {
            this.deliveryAutomation = deliveryAutomation;
            this.deliveryService = deliveryService;
            this.ordersService = ordersService;
            this.userService = userService;
        }

        // GET: Taxi
        public ActionResult Index()
        {
            List<DeliveryViewModel> model = deliveryAutomation.GetOrdersForStaff(CurrentUser.Id).Select(x => {
                var order = ordersService.GetOrderById(x);
                return new DeliveryViewModel()
                {
                    OrderID = order.OrderID,
                    AddressName = userService.GetUserAddress(order.AddressID).Name,
                    ETA = order.ETA
                };
            }).ToList();

            return View(model);
        }

        public EmptyResult SetETA(int orderId, int eta)
        {
            deliveryService.SetEstimatedArivalTime(orderId, eta);
            return new EmptyResult();
        }

        public EmptyResult MarkDelivered(int orderId)
        {
            deliveryService.MarkAsDelivered(orderId, true);
            deliveryAutomation.CompleteShipment(orderId, CurrentUser.Id);
            return new EmptyResult();
        }
    }
}

M19G2/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/AdminCss")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body style="padding-top: 0 !important">
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/admin">EAT SH.P.K</a>

        @if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm",  @class = "form-inline" }))
            {
                @Html.AntiForgeryToken()

                <ul class="navbar-nav right-nav px-3">
                    <li class="nav-item text-nowrap right-nav mr-3">
                        @Html.ActionLink("Account Settings", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", @class = "nav-link" })
                    </li>
                    <li class="nav-item right-nav text-nowrap"><a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                </ul>
            }
        }
    </nav>

    <div class="container-fluid">
        <div class="row">
            @Html.Partial("_AdminSidebar")

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                @RenderBody()
            </main>
        </div>
    </div>

    
</body>
</html>

M19G2/Views/Shared/_AdminSidebar.cshtml
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                @Html.ActionLink("System Users", "Index", "Admin", null, new {@class="nav-link side-link"})
            </li>
            <li class="nav-item">
                @Html.ActionLink("Create User", "Create", "Admin", null, new { @class = "nav-link side-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("System Logs", "Logs", "Admin", null, new { @class = "nav-link side-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Review Access Requests", "ReviewAccessRequests", "Admin", null, new { @class = "nav-link side-link" })
            </li>
        </ul>
    </div>
</nav>

M19G2/Views/Shared/_AuthenticationLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/authenticationCss")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body style="padding-top: 0 !important">
    @Html.Partial("_AccountNavbar")
    <div class="signin-container">

        @RenderBody()
    </div>

</body>
</html>

M19G2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EAT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body style="padding-top: 0 !important">
    @Html.Partial("_NavbarPartial")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E.A.T. ShPK</p>
        </footer>
    </div>

    
</body>
</html>

M19G2/Views/Shared/_NavbarPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    @Html.ActionLink("EAT", "Index", "Home", null, new { @class = "navbar-brand" })
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-i tem">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
            @if (User.IsInRole("Client"))
            {
                <li class="nav-item">@Html.ActionLink("Browse Dishes", "Index", "Dish", null, new { @class = "nav-link" })</li>
            }
            @if (User.IsInRole("Kitched Staff"))
            {
                <li class="nav-item">@Html.ActionLink("View Pending Orders", "Orders", "Account", null, new { @class = "nav-link" })</li>
            }
            @if (User.IsInRole("Chef"))
            {
                <li class="nav-item">@Html.ActionLink("Manage Dishes", "Index", "KitchenChef", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Ingredients", "IngredientsIndex", "KitchenChef", null, new { @class = "nav-link" })</li>
            }
            @if (User.IsInRole("Delivery Service Staff"))
            {
                <li class="nav-item">@Html.ActionLink("Pending Deliveries", "Index", "Taxi", null, new { @class = "nav-link" })</li>
            }
            <li class="nav-item">@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })</li>
            <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })</li>

        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</nav>

M19G2/Views/Shared/_cartListView.cshtml
@model M19G2.Models.CartViewModel

@{
    if (Model.Dishes.Count > 0)
    {
        foreach (var dd in Model.Quantities)
        {
            var d = Model.Dishes.Where(m => m.DishID == dd.Key).First();
            <div class="row border-bottom" style="padding: 8px">
                <div class="col-md-10">
                    <div id="space-time">
                        <div class="row">
                            <div class="col"><h5>@d.Name</h5></div>
                        </div>
                        <div class="row">
                            <div class="col-9">@d.Description</div>
                            <div class="col-3">
                                @Html.TextBoxFor(x => x.Quantities[d.DishID], new { @class = "form-control quantities", id = "quantitiy-" + d.DishID})
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div id="nuclear-fusion">
                        <div class="row">
                            <div class="col">Price: $@d.Price.ToString()</div>
                        </div>
                        <div class="row">
                            <div class="col">
                                @Html.ActionLink("Remove", "RemoveDish", "Cart", new { id = d.DishID }, new { @class = "btn btn-danger btn-sm dish-remove", id = d.DishID })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        if (Model.CalledFromNav)
        {
<div style="padding-top: 15px">
    @if (Model.UserAddresses.Count > 0)
    {
        using (Html.BeginForm("CompleteCheckout", "Cart", FormMethod.Post, new { model = Model }))
        {
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label class="lead font-weight-bold" for="deliveryAddress">Delivery Address</label>
                        @Html.DropDownList("deliveryAddress", Model.UserAddresses, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label class="lead font-weight-bold" for="extras">Extra Message</label>
                        <textarea class="form-control" name="extraDetails"></textarea>
                    </div>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary btn-md float-right">Checkout</button>
                </div>
            </div>
        }
    }
    else
    {
        <div class="row">
            <div class="col">
                   <p class="lead text-center">Please add a new address in order to proceed with the checkout.</p>
            </div>
        </div>
        Html.RenderPartial("_createUserAddress");
    }
</div>
        }
    }
    else
    {
        <div class="row border-bottom">
            <div class="col">
                <p class="text-xl-center">Your cart is empty.</p>
            </div>
        </div>
    }
}

<script>
    $(document).ready(function () {
        if ($('#createAddressPopup').length > 0) {
            $('#createAddressPopup').modal();
        }

        $('.quantities').change(e => {
            var id = e.target.id.split('-')[1];
            var quantity = $(e.target).val();

            CallGenericAjax("/Orders/SetQuantity?dishId=" + id + "&quantity=" + quantity,
            "text",
            null,
            false,
            null,
            "GET",
            null,
            null,
            (data) => {
               console.log("I DON'T KNOOOWWWW")
            },
            null);
        });

        /*$('#complete-checkout').click(e => {
            e.preventDefault();
        });*/
    });
</script>

M19G2/Views/Shared/_clientWelcome.cshtml
<div class="row">
    <div class="col-lg-6">
        <h4 class="text-center">Active Orders</h4>
        <hr />
        <div id="active-orders"></div>
    </div>

    <div class="col-lg-6">
        <h4 class="text-center">Old Orders</h4>
        <hr />
        <div id="orders-history"></div>
    </div>
</div>

<div class="modal fade" id="result-dialog" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resultDialogLabel">Hmm..</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="result-message"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Dismiss</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(() => {
        CallGenericAjax('@Url.Action("GetActiveOrders", "Orders")', "html", null, false, null, "GET", null, null, (data) => {
            $('#active-orders').html(data);
        }, null);
        CallGenericAjax('@Url.Action("GetOldOrders", "Orders")', "html", null, false, null, "GET", null, null, (data) => {
            $('#orders-history').html(data);
        }, null);
    });

    $(document).on('click', '.cancel-order', (e) => {
        var id = e.target.id;
        CallGenericAjax('/Orders/Cancel/' + id, "text", null, false, null, "GET", null, null, (data) => {
            $('#result-message').text(data);
            $('#result-dialog').modal();
            CallGenericAjax('@Url.Action("GetActiveOrders", "Orders")', "html", null, false, null, "GET", null, null, (data) => {
                 $('#active-orders').html(data);
            }, null);
        }, null);
    });
</script>

M19G2/Views/Shared/_createUserAddress.cshtml
<div class="modal fade" id="createAddressPopup" tabindex="-1" data-toggle="modal" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="title">Add new delivery address...</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid" id="popUpContainer">
                    @using (Html.BeginForm("CreateAddress", "Account"))
                    {
                        <div class="form-group">
                            <label class="font-weight-bold lead">Street Name</label>
                            <input type="text" class="form-control" name="addressName" />
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-sm float-right" type="submit">Create Address</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

M19G2/Views/Shared/_listActiveOrders.cshtml
@model M19G2.Models.OrderViewModel

<div class="w-100 mh-50">
    @if (Model.OrderDates != null && Model.Orders != null && Model.Orders.Count == Model.OrderDates.Count)
    {
        if (Model.OrderDates.Count > 0)
        {
            foreach (var v in Model.Orders)
            {
                <div class="row">
                    <div class="col-md-10">
                        <p class="lead font-weight-bold text-primary">@Model.OrderDates[v.Key]</p>
                        <p>
                            <ul class="list-group d-block">
                                @foreach (var dish in v.Value)
                                {
                                    <li class="list-group-item list-group-item-secondary">@dish</li>
                                }
                            </ul>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 p-1">
                        <button type="button" class="btn btn-primary cancel-order btn-sm btn-block" id="@v.Key.ToString()">Cancel Order</button>
                    </div>
                </div>
                <br />
            }
        }
        else
        {
            <div class="row">
                <div class="col">
                    <h4 class="lead text-center">Yikes, you've got nothing here :'(</h4>
                </div>
            </div>
        }
    }
</div>

M19G2/Views/Shared/_listOldOrders.cshtml
@model M19G2.Models.OrderViewModel

<div class="w-100 mh-100">
    @if (Model.OrderDates != null && Model.Orders != null && Model.Orders.Count == Model.OrderDates.Count)
    {
        if (Model.OrderDates.Count > 0)
        {
            foreach (var v in Model.Orders)
            {
                <div class="row">
                    <div class="col-md-10">
                        <p class="lead font-weight-bold text-primary text-right">@Model.OrderDates[v.Key]</p>
                        <p>
                            <ul class="list-group d-block">
                                @foreach (var dish in v.Value)
                                {
                                    <li class="list-group-item list-group-item-secondary">@dish</li>
                                }
                            </ul>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 p-1">
                        @Html.ActionLink("Order Again", "OrderAgain", "Orders", new { id = v.Key }, new { @class="btn btn-primary order-again btn-sm btn-block" })
                    </div>
                </div>
                <br />
            }
        }
        else
        {
            <div class="row">
                <div class="col">
                    <h4 class="lead text-center">Yikes, you've got nothing here :'(</h4>
                </div>
            </div>
        }
    }
</div>