M19G2/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace M19G2.Models
{
    public class OrderViewModel
    {
        public Dictionary<int, string[]> Orders { get; set; }

        public Dictionary<int, string> OrderDates { get; set; }

        public string PassingMessage { get; set; }  // which I should probably not use here
    }
}

M19G2/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using M19G2.Models;
using M19G2.IBLL;
using M19G2.SessionStorage;
using M19G2.Filters;
using System.IO;

namespace M19G2.Controllers
{
    public class DishController : BaseController
    {
        private readonly IDishService dishService;
        private readonly ISessionStorage sessionStorage;

        public DishController(IDishService dishService, ISessionStorage sessionStorage)
        {
            this.dishService = dishService;
            this.sessionStorage = sessionStorage;
        }

        [Authorize(Roles = "Client")]
        public ActionResult Index()
        {
            var cc = dishService.GetActiveDishes() as List<DishDto>;

            return View(new DishesViewModel() { Dishes = cc });
        }

        [HttpGet]
        public FileResult ShowImage(int dishId)
        {
            var dishesImgs = dishService.GetImagesForDish(dishId);
            ImageDto img;

            if (dishesImgs.Count > 0)
                img = dishesImgs.ElementAt(0);  // first image 
            else
                img = dishService.GetImageById(1);  // default image

            return File(img.Data, "image");
        }

        [HttpGet]
        public FileResult ShowDishImage(int imageId)
        {
            return File(dishService.GetImageById(imageId).Data, "image");
        }

        [Authorize(Roles = "Chef")]
        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase uploadedImage, int dishId)
        {
            using (MemoryStream memsr = new MemoryStream())
            {
                uploadedImage.InputStream.CopyTo(memsr);
                int imageId;
                dishService.UploadImage(memsr.ToArray(), dishId, out imageId);
            }
            return RedirectToAction("EditDish", "KitchenChef", new { id = dishId });
        }

        [Authorize]
        public ActionResult ViewDish(int id)
        {
            var dish = dishService.GetDishByID(id);

            return View("ViewDish", new ViewDishModel() { Dish = dish });
        }

        [Authorize(Roles = "Chef")]
        [HttpGet]
        public EmptyResult RemoveImage(int imageId)
        {
            dishService.RemoveImage(imageId);
            return new EmptyResult();
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult RenderDishFilter()
        {
            DishFilterViewModel model = new DishFilterViewModel
            {
                DishTypes = dishService.GetAllDishTypes().Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.Name }).ToList()
            };

            return PartialView("_DishesFilter", model);
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult Filter(string dishFilterName, string dishFilterTypeName, double? maxPrice, double? minPrice, string[] ingredients, bool? clearFilters)
        {
            var shit = new DishesViewModel()
            {
                Dishes = new List<DishDto>(),
                Types = new List<DishTypeDto>()
            };

            var filter = new Filter<DishDto>(dishService.GetActiveDishes());

           if(!clearFilters.HasValue || !clearFilters.Value)
            {
                if (!string.IsNullOrEmpty(dishFilterName))
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.Name.ToLower().Contains(dishFilterName.ToLower())));
                if (!string.IsNullOrEmpty(dishFilterTypeName))
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.DishType == int.Parse(dishFilterTypeName)));
                if (minPrice.HasValue)
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.Price >= (decimal)minPrice.Value));
                if (maxPrice.HasValue)
                    filter.FilterDefinitions.Add(new FilterDefinition<DishDto>(x => x.Price <= (decimal)maxPrice.Value));
                if (ingredients != null && ingredients.Length > 0)
                {
                    foreach (var ingredient in ingredients)
                        filter.FilterDefinitions.Add(new FilterDefinition<DishDto>((x) =>
                        {
                            foreach (var v in x.Ingredients)
                                if (v.Name == ingredient)
                                    return true;
                            return false;
                        }));  // huh this might take a bit..
                }
            }

            shit.Dishes = filter.ApplyFilters().ToList();

            return PartialView("_ListDishes", shit);
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult Remove(int id)
        {
            if (sessionStorage.IsOrderReady())
            {
                sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.RemoveAll(x => x == id);
            }
            var dishes = new List<DishDto>();
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.ForEach(did => dishes.Add(dishService.GetDishByID(did)));

            var orderReviewModel = new CartViewModel()
            {
                CurrentOrder = sessionStorage.GetCurrentOrder().CurrentOrder,
                Dishes = dishes
            };

            return PartialView("_cartListView", orderReviewModel);
        }

        [Authorize(Roles = "Client")]
        [HttpGet]
        public ActionResult Purchase(int id)
        {
            if (!sessionStorage.IsOrderReady())
                sessionStorage.ResetOrder(CurrentUser.Id);

            var dish = dishService.GetDishByID(id);
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.Add(id);

            var dishes = new List<DishDto>();
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.ForEach(did => {
                dishes.Add(dishService.GetDishByID(did));
            });

            var orderReviewModel = new CartViewModel()
            {
                CurrentOrder = sessionStorage.GetCurrentOrder().CurrentOrder,
                Dishes = dishes,
                Quantities = sessionStorage.GetCurrentOrder().Quantities
            };
            orderReviewModel.CalledFromNav = false;

            return PartialView("_cartReview", orderReviewModel);
        }
    }
}

M19G2/Controllers/HomeController.cs
using System.Web.Mvc;
using System;
using System.Text;
using M19G2.IBLL;
using M19G2.Models;
using M19G2.Common.Exceptions;

namespace M19G2.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IDishService dishService;
        private readonly IIngredientService ingredientService;
        private readonly IOrdersService ordersService;
        private readonly IDeliveryService deliveryService;

        public HomeController(IDishService dishService, IIngredientService ingredientService, IOrdersService orders, IDeliveryService delivery)
        {
            ordersService = orders;
            deliveryService = delivery;
            this.dishService = dishService;
            this.ingredientService = ingredientService;
        }

        public ActionResult Index()
        {
            var dishes = dishService.GetActiveDishes();
            return View(dishes);
        }

        [Authorize(Roles = "Client")]
        public ActionResult Orders()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

M19G2/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using M19G2.IBLL;
using M19G2.Models;
using M19G2.SessionStorage;

namespace M19G2.Controllers
{
    [Authorize]
    public class OrdersController : BaseController
    {
        private readonly IOrdersService ordersService;
        private readonly IDishService dishService;
        private readonly ISessionStorage sessionStorage;
        private readonly IOrderQueueService queueService;

        public OrdersController(IOrdersService ordersService, IDishService dishService, ISessionStorage sessionStorage,
            IOrderQueueService queueService)
        {
            this.queueService = queueService;
            this.ordersService = ordersService;
            this.dishService = dishService;
            this.sessionStorage = sessionStorage;
        }

        private OrderViewModel GetOrders(bool delivered)
        {
            var o = ordersService.ListOrdersForUser(CurrentUser.Id).Where(x => x.IsDelivered == delivered && x.Active).ToList();
            var orders = new Dictionary<int, string[]>();
            var orderDates = new Dictionary<int, string>();
            o.ForEach(order =>
            {
                var dNames = new List<string>();
                order.DishesIDs.ForEach(dish =>
                {
                    dNames.Add(dishService.GetDishByID(dish).Name);
                });
                orders.Add(order.OrderID, dNames.ToArray());
                orderDates.Add(order.OrderID, order.Created.ToString("dd/MM/yyy"));
            });

            return new OrderViewModel() { Orders = orders, OrderDates = orderDates };
        }

        [Authorize(Roles = "Kitched Staff")]
        [HttpGet]
        public ActionResult PeekDishes(int orderId)
        {
            List<string> model = new List<string>();

            ordersService.GetOrderById(orderId).DishesIDs.ForEach(x => model.Add(dishService.GetDishByID(x).Name));

            return PartialView("_listOrderDishes", model);
        }

        [HttpGet]
        public ActionResult GetActiveOrders()
        {
            return PartialView("_listActiveOrders", GetOrders(false));
        }

        [HttpGet]
        public ActionResult GetOldOrders()
        {
           return PartialView("_listOldOrders", GetOrders(true));
        }

        public ActionResult OrderAgain(int id)
        {
            var o = ordersService.GetOrderById(id);
            sessionStorage.SetOrder(new StorageOrder() { CurrentOrder = o });

            return RedirectToAction("Index", "Cart", new { completedPurchase = false });
        }

        [HttpGet]
        public ActionResult Cancel(int id)
        {
            var cc = DateTime.Now - ordersService.GetOrderById(id).Created;
            string Message = "";
            if (cc.Minutes <= 10)
            {
                ordersService.CancelOrder(id);
                Message = "That order has been canceled sir :)";
            }
            else
                Message = "You cannot cancel orders older than 10 minutes.";

            return Content(Message);
        }

        [HttpGet]
        public ActionResult Status(int orderId)
        {
            return Content(queueService.OrderStatus(orderId));
        }

        public EmptyResult SetQuantity(int dishId, int quantity)
        {
            /// could've been done better but who cares am i rite?
            sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.RemoveAll(x => x == dishId);
            for(int i = 0; i < quantity; i++)
                sessionStorage.GetCurrentOrder().CurrentOrder.DishesIDs.Add(dishId);

            return new EmptyResult();
        }
    }
}

M19G2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

M19G2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

M19G2/Views/Home/Index.cshtml
@using M19G2.Models
@model List<DishDto>

@{
    ViewBag.Title = "Home Page";
}

<style>

</style>
<style>
    .row-header {
        margin: 0px auto;
        padding: 0px auto;
    }

    .row-content {
        margin: 0px auto;
        padding: 50px 0px 50px 0px;
    }

    .footer {
        background-color: #d1c4e9;
        margin: 0px auto;
        padding: 20px 0px 20px 0px;
    }

    .jumbotron {
        padding: 70px 30px 70px 30px;
        margin: 0px auto;
        background: #9575cd;
        color: floralwhite;
    }

    .img-size{
        max-height: 150px;
        max-width: 150px;
    }

    .address {
        font-size: 80%;
        margin: 0px;
        color: #0f0f0f;
    }

    body {
        padding: 50px 0px 0px 0px;
        z-index: 0;
    }

    .navbar-dark {
        background-color: #512DA8;
    }

    .tab-content {
        border-left: 1px solid #ddd;
        border-right: 1px solid #ddd;
        border-bottom: 1px solid #ddd;
        padding: 10px;
    }
</style>

<header class="jumbotron">
    <div class="container">
        <div class="row row-header">
            <div class="col-12 col-sm-6">
                <h1>Ristorante EAT</h1>
                <p>
                    We take inspiration from the World's best cuisines, and add our own flavours to 
                    deliver the best service to our clients!
                </p>
            </div>
            <div class="col-12 col-sm-3 align-self-center">
                <img src="img/logo.png" alt="" class="img-fluid">
            </div>
            <div class="col-sm-3 align-self-center">
                 @Html.ActionLink("Make an order", "Index", "Dish", null, new { @class = "btn btn-warning btn-block" })
            </div>
        </div>
    </div>
</header>
@foreach(var dish in Model)
{

<div class="row row-content align-items-center">
    <div class="col-12 col-sm-4 order-sm-last col-md-3">
        <h3>Our Lipsmacking Culinary Creations</h3>
    </div>
    <div class="col col-sm col-md">
        <div class="media">
            <img src="/Dish/ShowImage?dishId=@dish.DishID" alt="athappypizza"
                    class="d-flex mr-3 img-thumbnail img-size align-self-center">
            <div class="media-body">
                <h2 class="mt-0">@dish.Name <i class="badge badge-primary">@dish.DishTypeName</i><i class="badge badge-pill badge-secondary">$@dish.Price</i></h2>
                <div class="d-none d-sm-block">
                    <p>@dish.Description</p>
                </div>
            </div>
        </div>
    </div>
</div>
}

<script>
        $(document).ready(function () {
            CallGenericAjax('@Url.Action("GetTop", "Statistics")',
            "html",
            null,
            false,
            null,
            "GET",
            null,
            null,
            (data) => {
                 $("#carouselShowPlace").html(data);
            },
            null);
        });
</script>

M19G2/Views/Home/Orders.cshtml
@{
    ViewBag.Title = "Your Orders";
}

<div class="row">
    <div class="col-lg-6">
        <h4 class="text-center">Active Orders</h4>
        <hr />
        <div id="active-orders"></div>
    </div>

    <div class="col-lg-6">
        <h4 class="text-center">Old Orders</h4>
        <hr />
        <div id="orders-history"></div>
    </div>
</div>

<div class="modal fade" id="result-dialog" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resultDialogLabel">Hmm..</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="result-message"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Dismiss</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(() => {
        CallGenericAjax('@Url.Action("GetActiveOrders", "Orders")', "html", null, false, null, "GET", null, null, (data) => {
            $('#active-orders').html(data);
        }, null);
        CallGenericAjax('@Url.Action("GetOldOrders", "Orders")', "html", null, false, null, "GET", null, null, (data) => {
            $('#orders-history').html(data);
        }, null);
    });

    $(document).on('click', '.cancel-order', (e) => {
        var id = e.target.id;
        CallGenericAjax('/Orders/Cancel/' + id, "text", null, false, null, "GET", null, null, (data) => {
            $('#result-message').text(data);
            $('#result-dialog').modal();
            CallGenericAjax('@Url.Action("GetActiveOrders", "Orders")', "html", null, false, null, "GET", null, null, (data) => {
                 $('#active-orders').html(data);
            }, null);
        }, null);
    });
</script>

M19G2/Views/Home/_kitchenStaffWelcome.cshtml
KITCHEN STAAF AAYY